print("goodmorning members")
print("wishing you a good day")
print("merge error")
print("solving merge error")
print("May God Bless members")
print("have a fruitful day")
print("I have cloned your project again during the day, Allow me create my branch named RoseProject and make further adjustmentss")
