print("goodmorning members")
print("wishing you a good day")
print("merge error")
print("solving merge error")
print("May God Bless members")
print("have a fruitful day")
print("I have cloned your project again during the day, Allow me create my branch named RoseProject and make further adjustmentss")
print("Merge Done, Everything shows in master")
print("Welcome branch RoseProject")
print("This content should only appear in this branch only")
print("If it appears in other branches i.e main,charity or David, then I should consult why!")
print("Testing double pushing from VS code")
print("Testing double pushing on the side of git hub")
