print("Welcome branch RoseProject")
print("This content should only appear in this branch only")
print("If it appears in other branches i.e main,charity or David, then I should consult why!")
print("Testing double pushing from VS code")
print("Testing double pushing on the side of git hub")
print("The project is now visible in the main after Merging? Team, Please explain this to me.")